### ISSUE TITLE
support for  Basler boA5120-230cm

### ISSUE THREAD

**Issue by LeeYangLBLBCS** [areaDetector/ADEuresys#1]
It appears this camera (Basler boA5120-230cm) is not one of the tested ones.
It has the same Coaxpress communication link.
Is there a chance it will work also?

**Comment by MarkRivers** [comment]
If it follows the GenICam standard then it should work.

**Comment by LeeYangLBLBCS** [comment]
I tried to compile on Windows 11 and Ubuntu 22.0.4 with the following egrabber driver, both got similar errors that look like below:
epics/base/include/compiler/msvc -IC:/epics/base/include/os/WIN32 -IC:/epics/base/include   -IC:/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADGenICam/include     -I"C:\Program Files\Euresys\eGrabber\include"    -c ../EuresysFeature.cpp
EuresysFeature.cpp
cl -EHsc -GR               -nologo -FC -D__STDC__=0 -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE    -Ox -GL -Oy-   -W3 -w44355 -w44344 -w44251 -D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING     -DH5_BUILT_AS_DYNAMIC_LIB    -MD -DEPICS_BUILD_DLL -DEPICS_CALL_DLL -TP   -I. -I../O.Common -I. -I. -I.. -I../../../include/compiler/msvc -I../../../include/os/WIN32 -I../../../include      -IC:/epics/modules/synApps_6_1_epics7/support/asyn-R4-45/include     -IC:/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADSupport/include/os/WIN32 -IC:/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADSupport/include   -IC:/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADCore/include -IC:/epics/base/include/compiler/msvc -IC:/epics/base/include/os/WIN32 -IC:/epics/base/include   -IC:/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADGenICam/include     -I"C:\Program Files\Euresys\eGrabber\include"    -c ../ADEuresys.cpp
ADEuresys.cpp
C:\epics\modules\synApps_6_1_epics7\support\areaDetector-R3-7\ADEuresys\EuresysApp\src\ADEuresys.cpp(140): error C2039: 'EGrabberClientVersion': is not a member of 'Euresys::Internal'
C:\Program Files\Euresys\eGrabber\include\internal\generated\ECameraBuffer.generated.h(9): note: see declaration of 'Euresys::Internal'
C:\epics\modules\synApps_6_1_epics7\support\areaDetector-R3-7\ADEuresys\EuresysApp\src\ADEuresys.cpp(140): error C2065: 'EGrabberClientVersion': undeclared identifier
gmake[3]: *** [C:/epics/base/configure/RULES_BUILD:267: ADEuresys.obj] Error 2
gmake[3]: Leaving directory 'C:/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADEuresys/EuresysApp/src/O.windows-x64'
gmake[2]: *** [C:/epics/base/configure/RULES_ARCHS:58: install.windows-x64] Error 2
gmake[2]: Leaving directory 'C:/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADEuresys/EuresysApp/src'
gmake[1]: *** [C:/epics/base/configure/RULES_DIRS:85: src.install] Error 2
gmake[1]: Leaving directory 'C:/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADEuresys/EuresysApp'
gmake: *** [C:/epics/base/configure/RULES_DIRS:85: EuresysApp.install] Error 2 

Windows version SDK: egrabber-win-x86_64-25.02.0.40.exe
Linux SDK: egrabber-linux-x86_64-25.02.0.39

Could the egrabber SDK have changed recently?

**Comment by MarkRivers** [comment]
ADEuresys is using 24.09.  Can you still download that older version?

**Comment by LeeYangLBLBCS** [comment]
Yes, the older SDK 24.09 fixed the compiler error.
Thanks.
